[package]
name = "trading"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
lazy_static = "1"
tokio = { version = "*", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }